# Generated by Django 6.0.2 on 2026-02-14 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='Jason Ololo', max_length=100),
        ),
    ]
