# Generated by Django 6.0.2 on 2026-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_livre_date_publication_alter_livre_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='devise',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='livre',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='livres_fichiers/'),
        ),
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
