# Generated by Django 6.0.2 on 2026-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField()),
            ],
        ),
    ]
