# Generated by Django 6.0.2 on 2026-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
