# Generated by Django 6.0.2 on 2026-02-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='videos_fichiers/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
