# Generated by Django 6.0.2 on 2026-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=200)),
                ('biographie', models.TextField()),
                ('photo', models.ImageField(upload_to='auteurs_photos/')),
            ],
        ),
    ]
