# Generated by Django 6.0.2 on 2026-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auteur',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterField(
            model_name='auteur',
            name='photo',
            field=models.ImageField(blank=True, upload_to='auteurs_photos/'),
        ),
    ]
